export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';
export const COUNTER_RESET = 'COUNTER_RESET';
export const COUNTER_INCREMENT_BY_VALUE = 'COUNTER_INCREMENT_BY_VALUE';
